### ISSUE TITLE
Add Template in Github Markdown

### ISSUE THREAD

**Issue by chris2k2** [arc42/arc42-template#107]
It would be nice to have a template in Github/GitLab markdown.

* Usage of Markdown, without the non supported extras currently used in the md packages
* Have "main file" of each chapter in a README.MD for a nice overview

This should be cool for github projects, who want to use markdown instead of asciidoc and for Gitlab users, since asciidoc is not supported there.

**Comment by chris2k2** [comment]
see PullRequest #108

**Comment by rdmueller** [comment]
> Usage of Markdown, without the non supported extras currently used in the md packages

What are the "non supported extras" - can you name them?

As I do understand, the already existing .md files need some extra modifications in order to directly use them on github and gitlab - correct?

Your files basically use the `readme.md` mechanism which automatically renders the files instead of having to click on them.

And these files only contain the structure, not the help texts.

So, in order to maintain all formats, we use the generator: https://github.com/arc42/arc42-generator . This repository contains the master written in AsciiDoc and this is transformed through build steps into several other formats.

I think we could add another step which transforms the multi page markdown which can be found here: https://github.com/arc42/arc42-template/blob/master/dist/arc42-template-EN-plain-markdownMP.zip into the desired format by renaming the files and maybe do some search and replace operations for the not supported extras.

what do you think?

**Comment by chris2k2** [comment]
> What are the "non supported extras" - can you name them?

Not all of them. I just noticed some things which did not work. I did not find anything on google, how they differ. The ones I saw are:

* Headers are usually done differently in github MD ( \# notation)
* Tables do not work the same 
* includes do not work
* references like used in the arc42 template do not work

> As I do understand, the already existing .md files need some extra modifications in order to directly use them on github and gitlab - correct?

Yes, that's right.

> what do you think?

 sounds like a way better solution and minimizes copy-pasting of all generic texts. I will check out the generator and see whether it is feasible.

Thanks for your feedback

**Comment by rdmueller** [comment]
with your github/gitlab template, it should be easy to check through a diff what exactly has to be changed from the original markdown files.

maybe we could apply those changes via regexp to the already existing md files in order to come up with github md files which look the same as yours (#108)?

if only I would have more time...

did you ever work with beyond compare? because this would give a great diff...
