### ISSUE TITLE
template (DE and EN) contain outdated ISO-25010 overview

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#159]
please fix the wrong ISO 25010 terms used within the template.

e.g. operability -> useability.

**Comment by mverburg** [comment]
I just happend to be looking into images in the hope I could refactor them to some form of textual form (e.g. PlantUML for the diagrams) and maybe some other form for illustrations such as the ISO-25010 overview.

The [asciidoc documentation](https://docs.asciidoctor.org/diagram-extension/latest/) has quite an extended list of tools that are supported. 

Using these textual forms would in my opinion help with (future) translations since only the language specific text would need to be changed instead of having to recreate a complete image.

Does that sound reasonable?

**Comment by gernotstarke** [comment]
good idea! If I remember correctly I have the ISO diagram in diagrams.net format, but maybe a PlantUML or Mermaid representation would be even better. Currently I don't find the time to evaluate these extensions, though... will discuss this with @rdmueller and @Hruschka next week!
