### ISSUE TITLE
create downloadable artifacts from build directory

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#16]
currently we only generate html into our build directory.

It'd be nice to copy all downloadable artifacts (e.g. the manually maintained EAP format, any manually maintained docx format, etc to the download directory, together with hashes etc

**Comment by rdmueller** [comment]
IMHO, travis does not make to much sense for these templates.
We do have the gh-pages branch and the dist folder is generated by the build. It is now easy to update the branch with the current dist files.
Those files are also linked from the landing page http://arc42.github.io .
Please reopen if you don't think that this issue is solved.
