### ISSUE TITLE
Sect 5, Building Block explanation, overly long bullet list (DE+EN)

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#163]
unify between DE and EN

**Comment by mverburg** [comment]
In order to keep the NL translation in sync as much as possible, I've checked the translation and concluded this issue is not applicable as it is based on the EN version. 

The change in the EN version is that the mid sentence line endings have been removed. While translating I'd taken the liberty to remove them already.

**Comment by gernotstarke** [comment]
change wording in DE version
