### ISSUE TITLE
create gh_page for arc42

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#41]
would be nice to have a github page with a nice "landing zone" - and maybe forwarding to confluence.arc42.org

**Comment by rdmueller** [comment]
hm. a landing page in the design of arc42.org with links to all downloadable templates? (https://github.com/arc42/arc42-template/tree/gh-pages/dist)
We could also use the "releases" feature of github https://github.com/arc42/arc42-template/releases

PS: what's the meaning of the "ready" tag? sound more like a milestone to me.

**Comment by gernotstarke** [comment]
"ready"-tag: inspired by https://waffle.io - an awesome way to manage github issues...

**Comment by gernotstarke** [comment]
concerning arc42.org: I'll be overhauling arc42.org asap (April, May?) - with a responsive design (RapidWeaver) UI template...

**Comment by gernotstarke** [comment]
gh_page: 

first thing is to have the arc42.github.io subdomain up-and-running... not urgent, but would be nice..

as we have so few content changes in arc42, I'm not that much interested in automating release processes...

**Comment by rdmueller** [comment]
> first thing is to have the arc42.github.io subdomain up-and-running

I don't have the needed permission to create the arc42/arc42.github.io repository. If you could create it for me (and give me write permission), I would install some jekyll templates in order to have some dynamic pages available.

as an alternative, I would create a landing page at http://arc42.github.io/arc42-template/ with an overview of the current templates and a link to arc42.org (just created a redirect page at this location)

**Comment by rdmueller** [comment]
what about this page as replacement for the current arc42.org download page? http://arc42.github.io/arc42-template/index2.html

**Comment by rdmueller** [comment]
http://arc42.github.io/

please comment if changes are needed or close this issue :-)

**Comment by rdmueller** [comment]
ok, changes to the landing page are now collected here: https://github.com/arc42/arc42.github.io/issues
