### ISSUE TITLE
create distinct repository for "template content" and "generator"

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#49]
as discussed between @rdmueller and myself during JAX-2015
- content-repo contains the master versions of the template in asciidoc, including help text
  and all required meta information, in all supported languages.
- content-repo contains a build that generates html versions of the available languages 
- generator-repo takes the content from content-repo and creates the various output formats
  (html, pdf, docx... with and without help, including one or several build-files for every version
- generator-repo moves/pushes the output of its build to the landing-page-download-directory...

does that sound plausible?

**Comment by rdmueller** [comment]
* content-repo contains a build that generates html versions of the available languages

I would let the generator-repo create the html versions. It could also push them (not ziped) to the .io repo to publish it as online example. Then we would have all online viewable and downloadable content in the .io repo.

another addition

* let's activate the .io wiki (https://github.com/arc42/arc42.github.io/wiki) and collect best practice on how to use the various format (e.g. how to build asciidoc with gradle/maven/etc ; which format is best used for github wikis ; how to work with confluence etc.)

what do you think?

**Comment by gernotstarke** [comment]
sounds ok to me...

we need to prototype that scenario:
1.) generator takes original source from content,
2.) creates html,
3.) copies to arc42.github.io repo

sounds difficult to me - especially because you created the arc42.github.io repo without a gh_pages branch... (or did I miss that one?)

**Comment by rdmueller** [comment]
arc42.github.io does not need a gh_pages branch because of its special function/name. It _is_ a gh_pages branch.

regarding the prototype: if the generator can assume that both other repositories are cloned into the same repository, it could just access those files and move them around (not many people will use this scenario).

But we could also add the content and .io repositories as subrepositories to the generator. This would ensure that the generator always has access to the other two repos, but it would add additional complexity...

IMHO, option 1 is ok since an automated build through travis or drone is currently not possible (because of dependencies to tools like pandoc). So we have to build and commit manually.

**Comment by gernotstarke** [comment]
please make it AS SIMPLE AS POSSIBLE...

(only you and me will ever use it, I assume...)

**Comment by rdmueller** [comment]
ok. option 1 :-)

I just wonder about the naming...

we currently have
* arc42.github.io
* arc42-template

and I would like to change that to
* arc42.github.io (stays the same)
* arc42-template-master (for the content)
* arc42-template-generator (for the build script)

...but I wonder about the arc42-template repository. If we re-use it by renaming it, some links might break. But IMHO, the name would not fit into the new schema. Maybe the best solution would be to leave it as is and mark it as deprecated with a link to the landing page and the other two repos.

**Comment by gernotstarke** [comment]
for me it would be ok to leave the existing arc42-template,
only reduce its responsibility to contain the master content only…

but you are free to decide. There are no important outside links I know of…

regards,
Gernot

**Comment by barthel** [comment]
arc42 is a template by definition.
So I would suggest the following repo structure:

* arc42-golden-master: where the golden master for the 'plain' ond the 'with-help' is located
* arc42-generator: for the toolchain (scripts)
* arc42.github.io

**Comment by rdmueller** [comment]
@barthel yes, I also agree that this structure sounds good. But I would stay with the naming "arc42-template". Maybe for the results of the generator.

**Comment by barthel** [comment]
@rdmueller What do you mean with:
> Maybe for the results of the generator.

What exactly is the result of the generator? The arc42 template with help texts?

So it is difficult to get in brain: The arc42-template repo contains the template for the arc42 template. 
So it is really important to use separate and unique names for both of them.
But it's my personal view.

The important task is to separate the toolchains from the golden master content.

**Comment by rdmueller** [comment]
thanx for the feedback! it is highly welcome.

the generator takes the golden master (asciidoc) and creates the several output formats like markdown.
So, a user of arc42 only needs one of the output formats.
A contributer needs to take a look at the golden master or generator.

> The important task is to separate the toolchains from the golden master content.
absolutely!

arc42-golden-master and arc42-generator are new repositories. I can easily create them over the weekend and we could start to move some files.

But I have to check how to bring the generator together with the golden-master... Subrepository?

**Comment by barthel** [comment]
> But I have to check how to bring the generator together with the golden-master... Subrepository?

That's a valid point.
From the modularity point of view we have to create a own project for the golden-master (contins only the content files) and consume this artifact in the generator project.

But this required a deployment to maven-central or similar.
It's charming to develop both in a separate timeline.
The generator must not be hard coupled with the golden-master and vice versa.

The second possibility is to use git-submodules. But it's more complicated than the mainstream git workflow.

The third and ugly solution is to use relative filesystem paths to navigate to the golden-master repo.

**Comment by rdmueller** [comment]
A binary repository like maven-central or bintray would be nice. I just imagine that I only have to state a dependency in my build and get the full template.

However, I have no experience with maven central or bintray. That's why I ould vote for the subrepository.

In addition, github handled the template-zip-files quite nice in the past. So I even would keep it this way for the moment: deploy the generated files to github pages...

What do you think? Shall we go this way as a first step?

**Comment by barthel** [comment]
Ok. I'm onboard.

I'm a maven guy and not familiar with gradle.
But I've experience to bring something to maven-central ;-).

**Comment by rdmueller** [comment]
@barthel can you send me an email so that we can exchange thoughts in a more direct way? You'll find my mail throught my profile...

**Comment by rdmueller** [comment]
@gernotstarke @barthel I would like to make some progress. If you agree, I would like to:

- create repo arc42-master for the two asciidoc master templates (with help)
- create repo arc42-generator for the gradle scripts which create all other templates
- arc42-template will contain the generated templates to be downloaded
- move https://github.com/arc42/arc42-template/tree/master/src/(DE|EN)/asciidoc/golden-master to arc42-master
- move the master branch of arc42-template to arc42-generator and modify it so that it uses arc42-master
- fork https://github.com/rdmueller/docToolchain . This will soon contain a gradle/maven multibuild for arc42

until now, these changes should be possible without breaking external dependencies. 
Next steps:

- change gh-pages branch of arc42-template to be the main branch
- replace the master branch of arc42-template with a hint that the code has been moved to arc42-master

Do you agree?

**Comment by gernotstarke** [comment]
Perfect, go ahead...

Best, Gernot 

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by rdmueller** [comment]
Update: I decided to clone the arc42-template repository into the arc42-master repository in order to keep the history. But since the files where moved within the repository, the github frontend will not show the full history.
Use `git log --follow .\01_introduction_and_goals.adoc` to retrieve the full history.

I will do the same for the arc42-generator

**Comment by rdmueller** [comment]
Update: first version of arc42-generator uses arc42-master as submodule and build the templates

Readme still needs an update

**Comment by rdmueller** [comment]
forked docToolchain to arc42

**Comment by rdmueller** [comment]
generator fixed for v6 template

**Comment by rdmueller** [comment]
@gernotstarke : here are the next steps we should do:

- arc42-generator is the new project which generates all other format from the golden master 
- arc42-master is the new golden master

- [ ]  we have to merge the new v7 version from arc42-template into the arc42-master (it is a clone from the master branch of arc42-template - don't know if this helps). The simplest way would be to copy the v7 version over as new version. In this case we would lose your edit history for the v7 template.
- [ ] afterwards we can discard the arc42-template
- [ ] we then have to generate the new arc42 version with the arc42-generator project and store the result wherever we like (arc42-template would be my suggestion)

I will now locally copy the v7 over and check that the generator works with v7

**Comment by rdmueller** [comment]
just checked the new generator vs old template project with v70 content - results are identical.

@gernotstarke as soon as you are finished with v70, I would like to merge it with full history into arc42-master

**Comment by gernotstarke** [comment]
Ralf,

arc42-template has 32 forks and 91 stars - whereas arc42-master has only two forks …

I suggest to:

* slightly modify your proposal below, to make „arc42-template“ the „golden master“…
* modify the documentation accordingly
* remove all the unneeded stuff from arc42-template (but we keep the history)
* later remove arc42-master

kind regards,
Gernot

**Comment by gernotstarke** [comment]
done:

arc42-template for the content,
arc42-generator for the generator.

perfect, will close this issue
