### ISSUE TITLE
gradlew.bat fails with Java 8

### ISSUE THREAD

**Issue by monora** [arc42/arc42-template#50]
Excuting gradlew under Java 8 fails:
```sh
d:/src/arc42-template $ ./gradlew.bat
Downloading https://services.gradle.org/distributions/gradle-1.12-bin.zip
...........................
* What went wrong:
A problem occurred evaluating settings 'arc42-template'.
> java/util/HashMap$Entry

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```
See also http://discuss.gradle.org/t/using-a-map-in-build-gradle-throws-noclassdeffounderror-ljava-util-hashmap-entry/7325

Using gradle 2.3 to fixes the problem.

**Comment by gernotstarke** [comment]
usually it shouldn't be required to build the template yourself, you should download one of the pre-built distributions...

We're currently updating the repo structure and content - so that you will get a more robust download and build environment (including sample gradle/maven build scripts together with the pure-template...)

sorry for the hassle,
Gernot

**Comment by gernotstarke** [comment]
we should update the gradle/gradlew build to a more recent gradle version...
