### ISSUE TITLE
gradlew createTemplatesFromGoldenMaster fails in :publish step

### ISSUE THREAD

**Issue by basbossink** [arc42/arc42-template#63]
I tried to run the above command but it fails. Running it with the `--stacktrace --debug` parameter gives the output as attached.

[publishFailure.txt](https://github.com/arc42/arc42-template/files/82628/publishFailure.txt)

**Comment by rdmueller** [comment]
Thanx for creating this issue...

FYI - all templates generated by this project are also available from http://arc42.github.io/ - so if you only need the templates, please download them from there...

Regarding the exception - just gave it a try on my windows system: it seems to work. I will now give it a try on a linux system...

**Comment by rdmueller** [comment]
hm. the build works for me on windows and linux.
the publish task is currently not used, but somehow your build fails because of this task.

I guess you problem will be resolved if you comment out this task:
https://github.com/arc42/arc42-template/blob/master/build.gradle#L140

**Comment by basbossink** [comment]
In hindsight I guess it makes sense that I'm not allowed to publish the locally generated templates to your github account. Maybe the getting started text can be amended to run a target in the gradle file that does not perform the publish task. Thanks for providing the link to all the templates I had not yet found them, that's why I was trying to generate them myself.

**Comment by rdmueller** [comment]
as far as I remeber, the publish target isn't even used by us. It was copied from another script and not removed. Out initial goal was to build and publish through travis, but we ran into problems with the available pandoc version of travis.

So, If you just want to use one of the templates which are build by this project, please head over to arc42.github.io and download it.

If you need to transform your documents, you might find good starting points on how to do it within this repository.

If you would like to help us improving the generated templates, the cleanness of our code etc., then I guess you need to be able to build this project.

I guess I should change the readme of this project in order to reflect the fact that most people only need to download the resulting templates and don't have to build the project.

And, as you said, I should change the build file to remove the publish task. 
I will open two new issues for these two tasks...

What is your goal? How can we assist you?

**Comment by rdmueller** [comment]
@basbossink the initial problem with the build script should now be resolve and thus I will close this issue now.
