### ISSUE TITLE
remove unneeded output formats

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#76]
keep:
docx, asciidoc, markdown, confluence

remove:
the rest (latex, textile, docbook, epub, markdownMP, html

**Comment by gernotstarke** [comment]
aah - the reason:

* imho too few people needs the others
* quality checks with all formats is too expensive (I manually checked markdown and docx,
both are seriously broken and not usable without modification.

**Comment by rdmueller** [comment]
hm. At least we should keep instructions on how to generate the other formats...

docbook - is an intermediate format for docx for instance
html - is nice to show the template on the net...
epub - I still dream of reading arc42 documents on an ebook reader

But I do understand that we should limit the formats in order to raise quality.

**Comment by gernotstarke** [comment]
epub: yes - a "completed" architecture documentation, but not the empty template...

I understand the requirement to keep docbook as intermediary - but I wouldn't offer it for download...

**Comment by rdmueller** [comment]
Ok.
All format can be easily configured in the generator. We just have to decide if we disable them already in the generator or just don't offer them for download.

For confluence, we still have to discuss the waye will generate it.

**Comment by gernotstarke** [comment]
close this - current state seems ok for everybody
